# notion Stack

version: '3.8'

networks:
  ingress:
    external: true
    name: ${INGRESS_NET}

services:
  nextjs:
    image: ${NEXTJS_IMAGE}
    environment:
      NOTION_TOKEN: ${NOTION_TOKEN}
      NOTION_VERSION: ${NOTION_VERSION}
      PAGE_ID: ${PAGE_ID}
    deploy:
      resources:
        limits:
          cpus: ${NEXTJS_CPU_LIMIT}
          memory: ${NEXTJS_MEMORY_LIMIT}
      replicas: ${NEXTJS_REPLICAS}
      placement:
        constraints:
          - node.labels.static.${NODE_LABEL} == 1
          - node.role == worker
      labels:
        - traefik.enable=true
        - traefik.docker.network=${INGRESS_NET}
        - traefik.constraint-label=${INGRESS_NET}
        - traefik.http.routers.${NAME}-notion-http.rule=Host(`${DOMAIN}`) || Host(`www.${DOMAIN}`)
        - traefik.http.routers.${NAME}-notion-http.entrypoints=http
        - traefik.http.routers.${NAME}-notion-http.middlewares=https-redirect
        - traefik.http.routers.${NAME}-notion-https.rule=Host(`${DOMAIN}`) || Host(`www.${DOMAIN}`)
        - traefik.http.routers.${NAME}-notion-https.entrypoints=https
        - traefik.http.routers.${NAME}-notion-https.tls=true
        - traefik.http.routers.${NAME}-notion-https.tls.certresolver=le
        - traefik.http.services.${NAME}-notion.loadbalancer.server.port=${WEB_SERVER_PORT-80}
    networks:
      - ingress


    